services:
  astro-template:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astro-template
    ports:
      - '4321:80'
    environment:
      - BACKEND_URL=http://localhost:3000
